import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET

# String Data
data = '''
<commentinfo>
<comments>
<comment>
<name>Raith</name>
<count>100</count>
</comment>
<comment>
<name>Meryl</name>
<count>100</count>
</comment>
<comment>
<name>Noah</name>
<count>94</count>
</comment>
<comment>
<name>Reynold</name>
<count>92</count>
</comment>
<comment>
<name>Cailaen</name>
<count>90</count>
</comment>
<comment>
<name>Jahid</name>
<count>90</count>
</comment>
<comment>
<name>Oriane</name>
<count>89</count>
</comment>
<comment>
<name>Tony</name>
<count>84</count>
</comment>
<comment>
<name>Rheo</name>
<count>83</count>
</comment>
<comment>
<name>Aziz</name>
<count>81</count>
</comment>
<comment>
<name>Lianne</name>
<count>72</count>
</comment>
<comment>
<name>Nickhill</name>
<count>72</count>
</comment>
<comment>
<name>Gael</name>
<count>69</count>
</comment>
<comment>
<name>Olufunke</name>
<count>68</count>
</comment>
<comment>
<name>Ayman</name>
<count>67</count>
</comment>
<comment>
<name>Daylen</name>
<count>65</count>
</comment>
<comment>
<name>Macy</name>
<count>65</count>
</comment>
<comment>
<name>Alana</name>
<count>64</count>
</comment>
<comment>
<name>JJ</name>
<count>63</count>
</comment>
<comment>
<name>Lana</name>
<count>62</count>
</comment>
<comment>
<name>Idris</name>
<count>61</count>
</comment>
<comment>
<name>Tammam</name>
<count>60</count>
</comment>
<comment>
<name>Jamey</name>
<count>58</count>
</comment>
<comment>
<name>Caela</name>
<count>55</count>
</comment>
<comment>
<name>Teresa</name>
<count>54</count>
</comment>
<comment>
<name>Tyson</name>
<count>54</count>
</comment>
<comment>
<name>Tegan</name>
<count>52</count>
</comment>
<comment>
<name>Blythe</name>
<count>50</count>
</comment>
<comment>
<name>Xaniamh</name>
<count>48</count>
</comment>
<comment>
<name>Esme</name>
<count>47</count>
</comment>
<comment>
<name>Mhea</name>
<count>44</count>
</comment>
<comment>
<name>Franko</name>
<count>40</count>
</comment>
<comment>
<name>Mowmita</name>
<count>39</count>
</comment>
<comment>
<name>Abiha</name>
<count>36</count>
</comment>
<comment>
<name>Joanne</name>
<count>33</count>
</comment>
<comment>
<name>Dylan</name>
<count>32</count>
</comment>
<comment>
<name>Nieve</name>
<count>31</count>
</comment>
<comment>
<name>Sammy</name>
<count>30</count>
</comment>
<comment>
<name>Anay</name>
<count>28</count>
</comment>
<comment>
<name>Cadey</name>
<count>27</count>
</comment>
<comment>
<name>Nuala</name>
<count>27</count>
</comment>
<comment>
<name>Jordyn</name>
<count>27</count>
</comment>
<comment>
<name>Kylan</name>
<count>26</count>
</comment>
<comment>
<name>Laina</name>
<count>25</count>
</comment>
<comment>
<name>Rico</name>
<count>22</count>
</comment>
<comment>
<name>Cormack</name>
<count>20</count>
</comment>
<comment>
<name>Kaine</name>
<count>15</count>
</comment>
<comment>
<name>Kiarrah</name>
<count>3</count>
</comment>
<comment>
<name>Kaleigh</name>
<count>2</count>
</comment>
<comment>
<name>Avraham</name>
<count>2</count>
</comment>
</comments>
</commentinfo>
'''

#count the total
tree = ET.fromstring(data)
lst = tree.findall('comments/comment')
print("comment counts:", len(lst))
t = 0
for item in lst:
    ct = int(item.find('count').text)
    t = t + ct
print(t)
